server:
  port: 8090
spring:
  ## Spring boot
  # cloud:
  #     config:
  #         uri: http://localhost:8888
  # application:
  #     name: DIRECTORY-SERVICE
  # Configurar la conexion a la base de datos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/directorio?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: tests
    password: w3sD0m
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    # Indicar el DBMSs
    database: MYSQL
    # Indica si debe mostrar el log de las consultas sql ejecutadas
    show-sql: true
    # Configurar Hibernate
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
